paths:
  word2vec: ../02-data/03-VSM/01-Word2Vec/word2vec-google-news-300.bin
  idf_cache: ../02-data/03-VSM/idf_cache_path.pkl
  word2vec_vsm_multivector: ../02-data/03-VSM/01-Word2Vec/word2vec-4-50-4-150-1.pkl
  word2vec_vsm_singlevector: ../02-data/03-VSM/01-Word2Vec/word2vec-4-50-4-150-0.pkl
  file: ../02-data/00-testing/batteries-non-rechargable-primary/1cr2/1cr2.txt
  output_path: ../02-data/00-testing/batteries-non-rechargable-primary/1cr2/sentence_expansions.txt
  pdf_folder: ../02-data/00-testing/
  retriever: ../02-data/05-Retrieval/corpus_bm25
  queries_1: ../02-data/06-Evaluation/query_evaluation_1.json
  queries_2: ../02-data/06-Evaluation/query_evaluation_2.json
  ranking_query_evaluation_1: ../02-data/06-Evaluation/ranking_query_evaluation_1.pkl
  ranking_query_evaluation_2: ../02-data/06-Evaluation/ranking_query_evaluation_2.pkl
  ranking_query_evaluation_3: ../02-data/06-Evaluation/ranking_query_evaluation_3.pkl
  ranking_query_evaluation_4: ../02-data/06-Evaluation/ranking_query_evaluation_4.pkl
  ranking_query_evaluation_5: ../02-data/06-Evaluation/ranking_query_evaluation_5.pkl
  ranking_query_evaluation_6: ../02-data/06-Evaluation/ranking_query_evaluation_6.pkl
  QE_eval: ../02-data/06-Evaluation/QE_eval.pkl
  no_QE_eval: ../02-data/06-Evaluation/no_QE_eval.pkl
  single_eval: ../02-data/06-Evaluation/single_eval.pkl
  multi_eval: ../02-data/06-Evaluation/multi_eval.pkl

save_file: ../02-data/06-Evaluation/multi_eval.pkl

use_multivector: true
use_expansion: true

norm_vsm: minmax
norm_bm25: zscore

top_k: 100